services:
  wildfhircemysql:
    image: aegisnetinc/wildfhirce-mysql:v0.5.1
    container_name: wildfhircemysql
    hostname: wildfhircemysql
    ports:
      - "3306:3306"
    volumes:
      - wildfhirce-mysql-data:/var/lib/mysql

  wildfhircewildfly:
    image: aegisnetinc/wildfhirce-wildfly:v0.5.1
    container_name: wildfhircewildfly
    hostname: wildfhircewildfly
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    depends_on:
      - wildfhircemysql

volumes:
  wildfhirce-mysql-data:
