services:
  wildfhircemysql:
    image: wildfhirce-mysql:r4-mysql8.0
    container_name: wildfhircemysql
    hostname: wildfhircemysql
    ports:
      - "3306:3306"
    volumes:
      - wildfhirce-mysql-data:/var/lib/mysql

  wildfhircewildfly:
    image: wildfhirce-wildfly:r4-20.0.1.Final-mysql8.0
    container_name: wildfhircewildfly
    hostname: wildfhircewildfly
    ports:
      - "80:80"
      - "443:443"
      - "9990:9990"
    depends_on:
      - wildfhircemysql

volumes:
  wildfhirce-mysql-data:
