-- =====================================================
-- WildFHIR R4 schema - PostgreSQL 18
-- Keep in sync with wildfhirr4_DDL_mysql.sql (same tables, columns,
-- lengths, index names and functions, all identifiers lowercase).
--
-- Run as a superuser (or a role with CREATEROLE) while connected to the
-- target database, e.g.:
--   psql -U postgres -d wildfhir -f wildfhirr4_DDL_postgres.sql
-- =====================================================

-- -----------------------------------------------------
-- Optional: create the database first (cannot run inside a transaction
-- block or a DO block; run separately, then connect to it).
-- The builtin C.UTF-8 locale gives code-point ordering, which lets the
-- ordinary btree indexes below also serve LIKE 'prefix%' searches.
-- -----------------------------------------------------
-- CREATE DATABASE wildfhirr4
--   ENCODING 'UTF8'
--   LOCALE_PROVIDER builtin
--   BUILTIN_LOCALE 'C.UTF-8'
--   TEMPLATE template0;

-- -----------------------------------------------------
-- Create application user (PostgreSQL has no CREATE USER IF NOT EXISTS)
-- -----------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wildfhiruser') THEN
    CREATE ROLE wildfhiruser LOGIN PASSWORD 'wildfhiruser';
  END IF;
END
$$;

BEGIN;

-- -----------------------------------------------------
-- Schema wildfhirr4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS wildfhirr4;
SET search_path TO wildfhirr4, public;

-- -----------------------------------------------------
-- Table wildfhirr4.code
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wildfhirr4.code (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
  codename         VARCHAR(64)  NOT NULL,
  value            VARCHAR(255) NOT NULL,
  intvalue         BIGINT       DEFAULT 0,
  description      VARCHAR(255) DEFAULT NULL,
  resourcecontents TEXT         DEFAULT NULL,
  CONSTRAINT code_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE wildfhirr4.code IS 'Code Table - WildFHIR configuration settings';


-- -----------------------------------------------------
-- Table wildfhirr4.conformance
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wildfhirr4.conformance (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
  resourceid       VARCHAR(255) NOT NULL,
  versionid        INTEGER      NOT NULL,
  resourcetype     VARCHAR(45)  NOT NULL,
  status           VARCHAR(45)  NOT NULL,
  lastuser         VARCHAR(255) DEFAULT NULL,
  lastupdate       TIMESTAMP(0) NOT NULL,
  resourcecontents TEXT         DEFAULT NULL,
  CONSTRAINT conformance_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE wildfhirr4.conformance IS 'Stores the CapabilityStatement resource for this server';


-- -----------------------------------------------------
-- Table wildfhirr4.serverdirectory
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wildfhirr4.serverdirectory (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name               VARCHAR(255)  NOT NULL,
  description        VARCHAR(255)  DEFAULT NULL,
  basepath           VARCHAR(2000) NOT NULL,
  lastuser           VARCHAR(45)   DEFAULT NULL,
  lastupdate         TIMESTAMP(0)  DEFAULT NULL,
  oauthgranttype     VARCHAR(45)   DEFAULT NULL,
  oauthclientid      VARCHAR(64)   DEFAULT NULL,
  oauthclientsecret  VARCHAR(255)  DEFAULT NULL,
  oauthusername      VARCHAR(255)  DEFAULT NULL,
  oauthpassword      VARCHAR(255)  DEFAULT NULL,
  oauthprivatekey    TEXT          DEFAULT NULL,
  oauthpublickey     TEXT          DEFAULT NULL,
  oauthscope         VARCHAR(2000) DEFAULT NULL,
  oauthauthurl       VARCHAR(2000) DEFAULT NULL,
  oauthtokenurl      VARCHAR(2000) DEFAULT NULL,
  oauthintrospecturl VARCHAR(2000) DEFAULT NULL,
  CONSTRAINT serverdirectory_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE wildfhirr4.serverdirectory IS 'FHIR server directory list';


-- -----------------------------------------------------
-- Table wildfhirr4.resource
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wildfhirr4.resource (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
  resourceid       VARCHAR(255) NOT NULL,
  versionid        INTEGER      NOT NULL,
  resourcetype     VARCHAR(45)  NOT NULL,
  status           VARCHAR(45)  NOT NULL,
  lastuser         VARCHAR(255) DEFAULT NULL,
  lastupdate       TIMESTAMP(0) NOT NULL,
  resourcecontents TEXT         DEFAULT NULL,
  sort0            VARCHAR(500) DEFAULT NULL,
  sort1            VARCHAR(500) DEFAULT NULL,
  sort2            VARCHAR(500) DEFAULT NULL,
  sort3            VARCHAR(500) DEFAULT NULL,
  sort4            VARCHAR(500) DEFAULT NULL,
  sort5            VARCHAR(500) DEFAULT NULL,
  sort6            VARCHAR(500) DEFAULT NULL,
  sort7            VARCHAR(500) DEFAULT NULL,
  sort8            VARCHAR(500) DEFAULT NULL,
  sort9            VARCHAR(500) DEFAULT NULL,
  CONSTRAINT resource_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE wildfhirr4.resource IS 'Stores current and history versions of a resource';

CREATE INDEX IF NOT EXISTS idx_resource_version
  ON wildfhirr4.resource (resourceid, versionid);

CREATE INDEX IF NOT EXISTS idx_resource_status_type
  ON wildfhirr4.resource (resourcetype, status);


-- -----------------------------------------------------
-- Table wildfhirr4.resourcemetadata
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wildfhirr4.resourcemetadata (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
  resourcejoinid INTEGER      NOT NULL,
  paramname      VARCHAR(127) NOT NULL,
  paramtype      VARCHAR(45)  NOT NULL,
  paramvalue     VARCHAR(670) DEFAULT NULL,
  systemvalue    VARCHAR(670) DEFAULT NULL,
  codevalue      VARCHAR(670) DEFAULT NULL,
  textvalue      VARCHAR(670) DEFAULT NULL,
  paramvalueu    VARCHAR(670) DEFAULT NULL,
  textvalueu     VARCHAR(670) DEFAULT NULL,
  CONSTRAINT resourcemetadata_pkey PRIMARY KEY (id),
  CONSTRAINT fk_resourcemetatdata_resource
    FOREIGN KEY (resourcejoinid)
    REFERENCES wildfhirr4.resource (id)
);

COMMENT ON TABLE wildfhirr4.resourcemetadata IS 'The current valid resource searchable metadata';

-- PostgreSQL does not auto-index foreign key columns; this one is required
CREATE INDEX IF NOT EXISTS fk_resourcemetatdata_resource_idx
  ON wildfhirr4.resourcemetadata (resourcejoinid);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_paramname
  ON wildfhirr4.resourcemetadata (paramname);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_paramnametype
  ON wildfhirr4.resourcemetadata (paramname, paramtype);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_paramvalue
  ON wildfhirr4.resourcemetadata (paramvalue);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_systemvalue
  ON wildfhirr4.resourcemetadata (systemvalue);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_codevalue
  ON wildfhirr4.resourcemetadata (codevalue);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_textvalue
  ON wildfhirr4.resourcemetadata (textvalue);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_paramvalueu
  ON wildfhirr4.resourcemetadata (paramvalueu);

CREATE INDEX IF NOT EXISTS idx_resourcemetadata_textvalueu
  ON wildfhirr4.resourcemetadata (textvalueu);


-- -----------------------------------------------------
-- Table wildfhirr4.subscriptionactivity
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wildfhirr4.subscriptionactivity (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
  subscriptionid VARCHAR(255)  NOT NULL,
  recorded       TIMESTAMP(0)  NOT NULL,
  type           VARCHAR(45)   NOT NULL,
  status         VARCHAR(45)   NOT NULL,
  description    VARCHAR(1000) NOT NULL,
  CONSTRAINT subscriptionactivity_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE wildfhirr4.subscriptionactivity IS 'Stores record of subscription activity';

CREATE INDEX IF NOT EXISTS idx_resourceid_status
  ON wildfhirr4.subscriptionactivity (subscriptionid, status);


-- -----------------------------------------------------
-- Function wildfhirr4.calcdistancekm
-- Great-circle (haversine) distance between two lat/lon points, in kilometers
-- -----------------------------------------------------
CREATE OR REPLACE FUNCTION wildfhirr4.calcdistancekm(
  lat1 DOUBLE PRECISION,
  lon1 DOUBLE PRECISION,
  lat2 DOUBLE PRECISION,
  lon2 DOUBLE PRECISION)
  RETURNS DOUBLE PRECISION
  LANGUAGE plpgsql
  IMMUTABLE PARALLEL SAFE
  COST 1
AS $BODY$
DECLARE
  dlat     DOUBLE PRECISION := radians(lat2 - lat1);
  dlon     DOUBLE PRECISION := radians(lon2 - lon1);
  a        DOUBLE PRECISION;
  c        DOUBLE PRECISION;
  distance DOUBLE PRECISION;
BEGIN
  a := sin(dlat/2) * sin(dlat/2) +
       cos(radians(lat1)) * cos(radians(lat2)) *
       sin(dlon/2) * sin(dlon/2);
  a := LEAST(a, 1.0); -- guard against rounding pushing a above 1 for near-antipodal points
  c := 2 * atan2(sqrt(a), sqrt(1-a));
  distance := 6371.0 * c; -- Earth's radius in kilometers
  RETURN distance;
END;
$BODY$;


-- -----------------------------------------------------
-- Function wildfhirr4.calcdistancemi
-- Great-circle (haversine) distance between two lat/lon points, in miles
-- -----------------------------------------------------
CREATE OR REPLACE FUNCTION wildfhirr4.calcdistancemi(
  lat1 DOUBLE PRECISION,
  lon1 DOUBLE PRECISION,
  lat2 DOUBLE PRECISION,
  lon2 DOUBLE PRECISION)
  RETURNS DOUBLE PRECISION
  LANGUAGE plpgsql
  IMMUTABLE PARALLEL SAFE
  COST 1
AS $BODY$
DECLARE
  dlat     DOUBLE PRECISION := radians(lat2 - lat1);
  dlon     DOUBLE PRECISION := radians(lon2 - lon1);
  a        DOUBLE PRECISION;
  c        DOUBLE PRECISION;
  distance DOUBLE PRECISION;
BEGIN
  a := sin(dlat/2) * sin(dlat/2) +
       cos(radians(lat1)) * cos(radians(lat2)) *
       sin(dlon/2) * sin(dlon/2);
  a := LEAST(a, 1.0); -- guard against rounding pushing a above 1 for near-antipodal points
  c := 2 * atan2(sqrt(a), sqrt(1-a));
  distance := 3959.0 * c; -- Earth's radius in miles
  RETURN distance;
END;
$BODY$;


-- -----------------------------------------------------
-- Grant privileges to wildfhiruser
-- (equivalent of GRANT SELECT,INSERT,UPDATE,DELETE,EXECUTE ON wildfhirr4.*)
-- -----------------------------------------------------
GRANT USAGE ON SCHEMA wildfhirr4 TO wildfhiruser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA wildfhirr4 TO wildfhiruser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA wildfhirr4 TO wildfhiruser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA wildfhirr4 TO wildfhiruser;

-- Cover objects created later in this schema by the role running this script
ALTER DEFAULT PRIVILEGES IN SCHEMA wildfhirr4
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wildfhiruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA wildfhirr4
  GRANT USAGE, SELECT ON SEQUENCES TO wildfhiruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA wildfhirr4
  GRANT EXECUTE ON FUNCTIONS TO wildfhiruser;

-- Let the application use unqualified table names (replaces MySQL "USE wildfhirr4")
ALTER ROLE wildfhiruser SET search_path = wildfhirr4, public;

COMMIT;
